
import { PrismaClient } from '@prisma/client';
import fs from 'fs';

const prisma = new PrismaClient();

async function main() {
    const projectId = '1a506ff3-bac6-4de1-8cab-3388ae7f47f6';

    const project = await prisma.project.findUnique({
        where: { id: projectId },
        include: {
            transactions: true,
        }
    });

    let output = '';
    const log = (msg: string) => { output += msg + '\n'; console.log(msg); };

    if (!project) {
        log('Project not found');
    } else {
        log('Project Details:');
        log(`Name: ${project.name}`);
        log(`Agreement Amount: ${project.agreementAmount}`);
        log(`Advance Paid (Static): ${project.advancePaid}`);
        log(`Remaining Amount (DB): ${project.remainingAmount}`);
        log(`Created At: ${project.createdAt.toISOString()}`);

        log('\nTransactions:');
        project.transactions.forEach(t => {
            log(`- ID: ${t.id}`);
            log(`  Type: ${t.type}`);
            log(`  Amount: ${t.amount}`);
            log(`  Desc: ${t.description}`);
            log(`  Date: ${t.transactionDate.toISOString()}`);

            // Check deduplication logic
            const isIncome = t.type === 'INCOME';
            const trxTime = new Date(t.transactionDate).getTime();
            const projTime = new Date(project.createdAt).getTime();
            const diff = Math.abs(trxTime - projTime);
            const isCloseTime = diff < 5 * 60 * 1000;
            const desc = (t.description || '').toLowerCase();
            const isAutoGenerated = desc.includes('advance payment for project');

            log(`  > Dedup Check: isIncome=${isIncome}, diff=${diff / 1000}s, isAuto=${isAutoGenerated} => SHOULD HIDE? ${isIncome && isCloseTime && isAutoGenerated}`);
            log('---');
        });
    }

    fs.writeFileSync('debug_output_utf8.txt', output, 'utf8');
}

main()
    .catch(e => console.error(e))
    .finally(async () => await prisma.$disconnect());
